version: '3'
services:
  postgres:
    image: 'postgres:16'
    container_name: postgres
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5433:5432'

  redis:
    image: 'redis:7.0'
    container_name: redis
    environment:
      - 'REDIS_PASSWORD=redis'
    ports:
      - '6379:6379'

  prometheus:
    image: 'prom/prometheus'
    container_name: prometheus
    ports:
      - '9090:9090'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - './config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml'

  grafana:
    image: 'grafana/grafana'
    container_name: grafana
    environment:
      - 'GF_SECURITY_ADMIN_USER=admin'
      - 'GF_SECURITY_ADMIN_PASSWORD=admin'
    ports:
      - '3000:3000'

  library-service:
    build: .
    container_name: library-service
    ports:
      - '8080:8080'
      - '1099:1099'